version: "3.3"

services:
  api:
    container_name: api
    build:
      context: ./api
    env_file: ./api/.env
    ports:
      - "3000:3000"
    networks:
      - mevn-dockerized
    command: ["npm", "start"]

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - mevn-dockerized
  server:
    container_name: static
    build:
      context: ./client
    ports:
      - "8080:8080"
    command: yarn run start
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb/mevn
    networks:
     - mevn-dockerized
networks:
  mevn-dockerized:
